"""Input providers for P0 HyperCloning validation.

The providers in this module intentionally only depend on the tokenizer/config
surface exposed by Hugging Face-style models. They do not inspect architecture
specific modules.
"""

from __future__ import annotations

from dataclasses import dataclass, field
import hashlib
import json
from pathlib import Path
from typing import Any, Protocol

import torch


FIXTURE_TEXTS: tuple[str, ...] = (
    "Hello world.",
    "The quick brown fox jumps over the lazy dog.",
    "日本語の文章を含むテストです。改行や句読点も確認します。",
    "def square(x):\n    return x * x\n",
    "Spaces    tabs\tand\nnewlines.",
    "Emoji test: 🧠🚀✨",
    "<s> [INST] test [/INST]",
    "A" * 512,
)


@dataclass
class InputMatrixSpec:
    """Configuration for random-token and tokenizer-backed input checks."""

    seq_lengths: tuple[int, ...] = (8, 32, 128)
    batch_size: int = 2
    num_random_batches_per_length: int = 2
    seed: int = 0
    random_batches: bool = True
    tokenizer_fixture_batches: bool = True
    chat_template_batches: bool = True
    local_text_file: str | None = None
    max_fixture_texts: int = 8
    include_left_padding: bool = True
    include_right_padding: bool = True
    include_high_id_tokens: bool = True
    include_special_token_cases: bool = True
    add_special_tokens: bool = True
    include_labels: bool = True
    pad_token_id: int | None = None


@dataclass
class BatchBundle:
    """Named group of batches generated by one provider/scenario."""

    name: str
    batches: list[dict[str, torch.Tensor]]
    metadata: dict[str, Any] = field(default_factory=dict)


class BatchProvider(Protocol):
    name: str

    def make_batches(self, tokenizer: Any | None, config: Any | None, spec: InputMatrixSpec) -> list[BatchBundle]:
        ...


def _get_config_value(config: Any | None, names: tuple[str, ...], default: Any = None) -> Any:
    if config is None:
        return default
    for name in names:
        if hasattr(config, name):
            return getattr(config, name)
    if isinstance(config, dict):
        for name in names:
            if name in config:
                return config[name]
    return default


def infer_vocab_size(tokenizer: Any | None = None, config: Any | None = None) -> int:
    value = _get_config_value(config, ("vocab_size", "n_vocab"), None)
    if value is not None:
        return int(value)
    if tokenizer is not None:
        try:
            return int(len(tokenizer))
        except Exception:
            pass
        value = getattr(tokenizer, "vocab_size", None)
        if value is not None:
            return int(value)
    raise ValueError("Could not infer vocab size from config or tokenizer")


def infer_pad_token_id(tokenizer: Any | None, spec: InputMatrixSpec) -> int:
    if spec.pad_token_id is not None:
        return int(spec.pad_token_id)
    if tokenizer is not None:
        for attr in ("pad_token_id", "eos_token_id", "bos_token_id", "unk_token_id"):
            value = getattr(tokenizer, attr, None)
            if value is not None:
                return int(value)
    return 0


def _labels_from_ids(input_ids: torch.Tensor, attention_mask: torch.Tensor | None, include_labels: bool) -> torch.Tensor | None:
    if not include_labels:
        return None
    labels = input_ids.clone()
    if attention_mask is not None:
        labels = labels.masked_fill(attention_mask == 0, -100)
    return labels


def _bundle_batch(input_ids: torch.Tensor, attention_mask: torch.Tensor | None, include_labels: bool) -> dict[str, torch.Tensor]:
    batch: dict[str, torch.Tensor] = {"input_ids": input_ids.long()}
    if attention_mask is not None:
        batch["attention_mask"] = attention_mask.long()
    labels = _labels_from_ids(input_ids, attention_mask, include_labels)
    if labels is not None:
        batch["labels"] = labels.long()
    return batch


def tokenizer_fingerprint(tokenizer: Any | None) -> dict[str, Any]:
    if tokenizer is None:
        return {"available": False}
    special_map = getattr(tokenizer, "special_tokens_map", None)
    chat_template = getattr(tokenizer, "chat_template", None)
    return {
        "available": True,
        "class": type(tokenizer).__name__,
        "vocab_size": getattr(tokenizer, "vocab_size", None),
        "length": len(tokenizer) if hasattr(tokenizer, "__len__") else None,
        "bos_token_id": getattr(tokenizer, "bos_token_id", None),
        "eos_token_id": getattr(tokenizer, "eos_token_id", None),
        "pad_token_id": getattr(tokenizer, "pad_token_id", None),
        "unk_token_id": getattr(tokenizer, "unk_token_id", None),
        "special_tokens_map": dict(special_map) if isinstance(special_map, dict) else special_map,
        "chat_template_sha256": hashlib.sha256(str(chat_template).encode("utf-8")).hexdigest() if chat_template else None,
    }


class RandomTokenProvider:
    name = "random_tokens"

    def make_batches(self, tokenizer: Any | None, config: Any | None, spec: InputMatrixSpec) -> list[BatchBundle]:
        vocab_size = infer_vocab_size(tokenizer, config)
        pad_token_id = infer_pad_token_id(tokenizer, spec)
        gen = torch.Generator(device="cpu")
        gen.manual_seed(spec.seed)
        bundles: list[BatchBundle] = []

        for seq_len in spec.seq_lengths:
            batches = []
            for batch_i in range(spec.num_random_batches_per_length):
                ids = torch.randint(1, max(vocab_size, 2), (spec.batch_size, seq_len), generator=gen, dtype=torch.long)
                mask = torch.ones_like(ids)
                if spec.include_right_padding and batch_i % 3 == 1:
                    pad_len = max(1, seq_len // 4)
                    ids[:, -pad_len:] = pad_token_id
                    mask[:, -pad_len:] = 0
                elif spec.include_left_padding and batch_i % 3 == 2:
                    pad_len = max(1, seq_len // 4)
                    ids[:, :pad_len] = pad_token_id
                    mask[:, :pad_len] = 0
                batches.append(_bundle_batch(ids, mask, spec.include_labels))
            bundles.append(BatchBundle(f"random.seq{seq_len}", batches, {"seq_len": seq_len, "vocab_size": vocab_size}))

            if spec.include_high_id_tokens and vocab_size > 8:
                high = torch.arange(vocab_size - seq_len, vocab_size, dtype=torch.long).clamp_min(1)
                if high.numel() < seq_len:
                    high = high.repeat((seq_len // max(high.numel(), 1)) + 1)[:seq_len]
                ids = high.unsqueeze(0).repeat(spec.batch_size, 1)
                mask = torch.ones_like(ids)
                bundles.append(BatchBundle(f"random.high_id.seq{seq_len}", [_bundle_batch(ids, mask, spec.include_labels)], {"seq_len": seq_len}))

            if spec.include_special_token_cases:
                special_ids = [pad_token_id]
                if tokenizer is not None:
                    for attr in ("bos_token_id", "eos_token_id", "unk_token_id"):
                        value = getattr(tokenizer, attr, None)
                        if value is not None:
                            special_ids.append(int(value))
                special_ids = [x for x in dict.fromkeys(special_ids) if 0 <= int(x) < vocab_size]
                if special_ids:
                    row = torch.tensor((special_ids * ((seq_len // len(special_ids)) + 1))[:seq_len], dtype=torch.long)
                    ids = row.unsqueeze(0).repeat(spec.batch_size, 1)
                    mask = torch.ones_like(ids)
                    bundles.append(BatchBundle(f"random.special.seq{seq_len}", [_bundle_batch(ids, mask, spec.include_labels)], {"seq_len": seq_len, "special_ids": special_ids}))

        return bundles


class TokenizerFixtureProvider:
    name = "tokenizer_fixtures"

    def __init__(self, texts: tuple[str, ...] = FIXTURE_TEXTS):
        self.texts = texts

    def make_batches(self, tokenizer: Any | None, config: Any | None, spec: InputMatrixSpec) -> list[BatchBundle]:
        if tokenizer is None:
            return []
        texts = list(self.texts[: spec.max_fixture_texts])
        pad_token_id = infer_pad_token_id(tokenizer, spec)
        bundles: list[BatchBundle] = []

        old_padding_side = getattr(tokenizer, "padding_side", None)
        sides = ["right"]
        if spec.include_left_padding:
            sides.append("left")

        try:
            for seq_len in spec.seq_lengths:
                for side in sides:
                    if old_padding_side is not None:
                        tokenizer.padding_side = side
                    encoded = tokenizer(
                        texts,
                        padding=True,
                        truncation=True,
                        max_length=seq_len,
                        return_tensors="pt",
                        add_special_tokens=spec.add_special_tokens,
                    )
                    input_ids = encoded["input_ids"]
                    attention_mask = encoded.get("attention_mask", torch.ones_like(input_ids))
                    batches = []
                    for start in range(0, input_ids.shape[0], spec.batch_size):
                        end = min(start + spec.batch_size, input_ids.shape[0])
                        ids = input_ids[start:end]
                        mask = attention_mask[start:end]
                        if ids.numel() == 0:
                            continue
                        batches.append(_bundle_batch(ids, mask, spec.include_labels))
                    bundles.append(BatchBundle(f"tokenizer.{side}.seq{seq_len}", batches, {"seq_len": seq_len, "padding_side": side, "pad_token_id": pad_token_id}))
        finally:
            if old_padding_side is not None:
                tokenizer.padding_side = old_padding_side
        return bundles


class LocalTextProvider:
    name = "local_text"

    def make_batches(self, tokenizer: Any | None, config: Any | None, spec: InputMatrixSpec) -> list[BatchBundle]:
        if tokenizer is None or not spec.local_text_file:
            return []
        path = Path(spec.local_text_file)
        if not path.exists():
            raise FileNotFoundError(path)
        texts = [line.strip() for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]
        if not texts:
            return []
        return TokenizerFixtureProvider(tuple(texts[: spec.max_fixture_texts])).make_batches(tokenizer, config, spec)


class ChatTemplateProvider:
    name = "chat_template"

    def make_batches(self, tokenizer: Any | None, config: Any | None, spec: InputMatrixSpec) -> list[BatchBundle]:
        if tokenizer is None or not hasattr(tokenizer, "apply_chat_template"):
            return []
        if getattr(tokenizer, "chat_template", None) is None:
            return []
        conversations = [
            [{"role": "user", "content": "Hello."}],
            [{"role": "user", "content": "日本語で短く説明してください。"}, {"role": "assistant", "content": "はい。"}],
        ]
        texts = []
        for conv in conversations:
            try:
                text = tokenizer.apply_chat_template(conv, tokenize=False, add_generation_prompt=True)
            except Exception:
                continue
            texts.append(str(text))
        if not texts:
            return []
        bundles = TokenizerFixtureProvider(tuple(texts)).make_batches(tokenizer, config, spec)
        for bundle in bundles:
            bundle.name = "chat_template." + bundle.name
        return bundles


def make_input_matrix(tokenizer: Any | None, config: Any | None, spec: InputMatrixSpec | None = None) -> list[BatchBundle]:
    spec = spec or InputMatrixSpec()
    providers: list[BatchProvider] = []
    if spec.random_batches:
        providers.append(RandomTokenProvider())
    if spec.tokenizer_fixture_batches:
        providers.append(TokenizerFixtureProvider())
    if spec.chat_template_batches:
        providers.append(ChatTemplateProvider())
    if spec.local_text_file:
        providers.append(LocalTextProvider())

    bundles: list[BatchBundle] = []
    for provider in providers:
        try:
            bundles.extend(provider.make_batches(tokenizer, config, spec))
        except Exception as exc:
            bundles.append(BatchBundle(f"{provider.name}.error", [], {"error": repr(exc)}))
    return bundles


def bundles_to_jsonable(bundles: list[BatchBundle]) -> list[dict[str, Any]]:
    return [
        {"name": b.name, "num_batches": len(b.batches), "metadata": b.metadata}
        for b in bundles
    ]


def fingerprint_to_json(fingerprint: dict[str, Any]) -> str:
    return json.dumps(fingerprint, ensure_ascii=False, sort_keys=True)
